spring:
  # Hibernate / JPA
  jpa:
    hirenate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    # Postgres
    url: jdbc:h2:mem:healthy_life_test;
    driver-class-name: org.h2.Driver
    username: sa
    # Flyway
    flyway:
      url: jdbc:h2:mem:healthy_life_test;
      user: sa
      baseline-on-migrate: true